import { Button } from '@material-ui/core'
import Head from 'next/head'

export const IndexPublicWeb = () => {
  return (
    <div>
      <Head>
        <title>Public SSR web</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1>Public SSR web</h1>
      </div>

      <Button variant='outlined'>my Btn!</Button>
    </div>
  )
}
